export const categoryActionTypes = {
    ADD_CATEGORY:"ADD_CATEGORY",
    EDIT_CATEGORY:"EDIT_CATEGORY",
    DELETE_CATEGORY:"DELETE_CATEGORY",
    ADD_SUB_CATEGORY:"ADD_SUB_CATEGORY",
    EDIT_SUB_CATEGOTY:"EDIT_SUB_CATEGOTY",
    DELETE_SUB_CATEGORY:"DELETE_SUB_CATEGORY"
}